[project]
name = "tiny-llm-app"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "fastapi[standard]>=0.115.12",
    "jupyter>=1.1.1",
    "pre-commit>=4.2.0",
    "ruff>=0.11.5",
    "streamlit>=1.44.1",
]
